#########################################################################
# Title:         Cloudbox: Rclone - Import config                       #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Check if 'rclone.conf' exists in '{{playbook_dir}}' folder"
  stat:
    path: "{{playbook_dir}}/rclone.conf"
  register: rclone_conf_playbook_dir

- name: "Check if 'rclone.conf' exists in default location"
  stat:
    path: "/home/{{user}}/.config/rclone/rclone.conf"
  register: rclone_conf_default_path

- name: "Backup existing 'rclone.conf' at default location (if it exists) 1/2"
  copy:
    src: "/home/{{user}}/.config/rclone/rclone.conf"
    dest: "/home/{{user}}/.config/rclone/rclone.conf.bak"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: yes
  when: rclone_conf_playbook_dir.stat.exists and rclone_conf_default_path.stat.exists

- name: "Backup existing 'rclone.conf' at default location (if it exists) 2/2"
  file:
    path: "/home/{{user}}/.config/rclone/rclone.conf"
    state: absent
  when: rclone_conf_playbook_dir.stat.exists and rclone_conf_default_path.stat.exists

- name: "Copy 'rclone.conf' from '{{playbook_dir}}' folder to default location"
  copy:
    src: "{{playbook_dir}}/rclone.conf"
    dest: "/home/{{user}}/.config/rclone/rclone.conf"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: yes
  when: rclone_conf_playbook_dir.stat.exists

- name: "Remove the 'rclone.conf' copy from the '{{playbook_dir}}' folder"
  file: "path={{item}} state=absent"
  with_items:
    - "{{playbook_dir}}/rclone.conf"
  when: rclone_conf_playbook_dir.stat.exists

- name: "Check if 'rclone.conf' exists at default location"
  stat:
    path: "/home/{{user}}/.config/rclone/rclone.conf"
  register: rclone_conf_default_path_2

- name: "Do the following block when 'rclone.conf' is not at default location"
  block:

  - name: "Find location of 'rclone.conf' when not at default location"
    shell: rclone config file
    register: rclone_conf_current_location

  - name: "Copy 'rclone.conf' to default location if found elsewhere"
    copy:
      src: "{{ rclone_conf_current_location.stdout_lines | last }}"
      dest: "/home/{{user}}/.config/rclone/rclone.conf"
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0775
      force: yes
    when: rclone_conf_current_location.stdout.find('Configuration file doesn\'t exist') == -1

  - name: "Remove that other 'rclone.conf' copy"
    file:
      path: "{{ rclone_conf_current_location.stdout_lines | last }}"
      state: absent
    when: rclone_conf_current_location.stdout.find('Configuration file doesn\'t exist') == -1

  - name: "Create blank 'rclone.conf' if not found elsewhere"
    file:
      path: "/home/{{user}}/.config/rclone/rclone.conf"
      state: touch
      mode: 0775
      owner: "{{user}}"
      group: "{{user}}"
    when: rclone_conf_current_location.stdout.find('Configuration file doesn\'t exist') != -1

  when: not rclone_conf_default_path_2.stat.exists
