#########################################################################
# Title:         Cloudbox: Rclone Role                                  #
# Author(s):     L3uddz, Desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Install common packages
  apt: "name={{item}} state=present"
  with_items:
    - unzip
    - man-db

- name: Create rclone directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=yes"
  with_items:
    - "/home/{{user}}/.config"
    - "/home/{{user}}/.config/rclone"

- name: "Legacy rclone uninstaller"
  include_tasks: "legacy_uninstaller.yml"

- name: Cleanup rclone tmp path
  shell: rm -rf /tmp/rclone-*-linux-amd64
  args:
    warn: no

- name: Check if rclone version was specified
  set_fact:
    rclone_version_is_specified: "{{ true if not (
        (rclone is undefined)
        or
        (rclone is none)
        or
        (rclone | trim == '')
        or
        (rclone.version is undefined)
        or
        (rclone.version is none)
        or
        (rclone.version | trim == '')
      )
      else false }}"

- name: Set rclone_download_url for current version
  set_fact:
    rclone_download_url: "https://downloads.rclone.org/rclone-current-linux-amd64.zip"
  when: (not rclone_version_is_specified) or (rclone.version == 'latest') or (rclone.version == 'current')

- name: Set rclone_download_url for beta version
  set_fact:
    rclone_download_url: "https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip"
  when: (rclone_version_is_specified) and (rclone.version == 'beta')

- name: Set rclone_download_url for specified version
  set_fact:
    rclone_download_url: 'https://downloads.rclone.org/v{{ "%.2f"|format(rclone.version) }}/rclone-v{{ "%.2f"|format(rclone.version) }}-linux-amd64.zip'
  when: (rclone_version_is_specified) and not ((rclone.version == 'beta') or (rclone.version == 'latest') or (rclone.version == 'current'))
  ignore_errors: yes

- name: "Download and unarchive rclone"
  unarchive:
    src: "{{ rclone_download_url | default('https://downloads.rclone.org/rclone-current-linux-amd64.zip',true) }}"
    dest: /tmp
    copy: no
    validate_certs: no

- name: Find rclone tmp dir
  shell: ls -d /tmp/rclone-*-linux-amd64
  register: rclone_tmp_dir

- name: Copy binary to /usr/bin/rclone
  copy:
    src: "{{ rclone_tmp_dir.stdout }}/rclone"
    dest: "/usr/bin/rclone"
    mode: 0775
    owner: root
    group: root
    force: yes

- name: Make dir for local manpages
  file:
    path: '/usr/local/share/man/man1'
    state: directory
    mode: 0775
    owner: root
    group: root

- name: Copy manpage
  copy:
    src: "{{ rclone_tmp_dir.stdout }}/rclone.1"
    dest: /usr/local/share/man/man1/rclone.1
    mode: 0664
    owner: root
    group: root

- name: Install manpage
  shell: mandb
  changed_when: false

- name: Get rclone version
  shell: rclone --version | head -n 1 | awk '{ print substr($2, 2) }'
  register: rclone_version
  ignore_errors: yes

- name: "Display rclone version"
  debug:
    msg: "Rclone {{rclone_version.stdout}} installed."

- name: "Check if 'rclone.conf' exists in '{{playbook_dir}}' folder"
  stat:
    path: "{{playbook_dir}}/rclone.conf"
  register: rclone_conf_playbook_dir

- name: "Check if 'rclone.conf' exists in default location"
  stat:
    path: "/home/{{user}}/.config/rclone/rclone.conf"
  register: rclone_conf_default_path

- name: "Backup existing 'rclone.conf' at default location (if it exists)"
  shell: "mv '/home/{{user}}/.config/rclone/rclone.conf' '/home/{{user}}/.config/rclone/rclone.conf.bak'"
  when: rclone_conf_playbook_dir.stat.exists and rclone_conf_default_path.stat.exists

- name: "Copy 'rclone.conf' from '{{playbook_dir}}' folder to default location"
  copy:
    src: "{{playbook_dir}}/rclone.conf"
    dest: "/home/{{user}}/.config/rclone/rclone.conf"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: yes
  when: rclone_conf_playbook_dir.stat.exists

- name: "Remove the 'rclone.conf' copy from the '{{playbook_dir}}' folder"
  file: "path={{item}} state=absent"
  with_items:
    - "{{playbook_dir}}/rclone.conf"
  when: rclone_conf_playbook_dir.stat.exists

- name: "Check if 'rclone.conf' exists at default location"
  stat:
    path: "/home/{{user}}/.config/rclone/rclone.conf"
  register: rclone_conf_default_path_2

- name: "Do the following block when 'rclone.conf' is not at default location"
  block:

  - name: "Find location of 'rclone.conf' when not at default location"
    shell: rclone config file
    register: rclone_conf_current_location

  - name: "Copy 'rclone.conf' to default location if found elsewhere"
    copy:
      src: "{{ rclone_conf_current_location.stdout_lines | last }}"
      dest: "/home/{{user}}/.config/rclone/rclone.conf"
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0775
      force: yes
    when: rclone_conf_current_location.stdout.find('Configuration file doesn\'t exist') == -1

  - name: "Remove that other 'rclone.conf' copy"
    file: "path={{item}} state=absent"
    with_items:
      - "{{ rclone_conf_current_location.stdout_lines | last }}"
    when: rclone_conf_current_location.stdout.find('Configuration file doesn\'t exist') == -1

  - name: "Create blank 'rclone.conf' if not found elsewhere"
    file:
      path: "/home/{{user}}/.config/rclone/rclone.conf"
      state: touch
      mode: 0775
      owner: "{{user}}"
      group: "{{user}}"
    when: rclone_conf_current_location.stdout.find('Configuration file doesn\'t exist') != -1

  when: not rclone_conf_default_path_2.stat.exists
