version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: sudo apt-get install software-properties-common
      - run: sudo apt-add-repository ppa:ansible/ansible -y
      - run: sudo apt-get update
      - run: sudo apt-get install ansible -y
      - run:
          name: "run ansible-playbook for continuous integration"
          command: sudo ansible-playbook cloudbox.yml --tags "cloudbox" --skip-tags "settings" --extra-vars '{"continuous_integration":true}'
