version: 2
jobs:
  build:
    machine: 
      image: circleci/classic:201808-01
    steps:
      - run: sudo apt-get install software-properties-common
      - run: sudo apt-add-repository ppa:ansible/ansible -y
      - run: sudo add-apt-repository ppa:git-core/ppa -y
      - run: sudo apt-get update
      - run: sudo apt-get dist-upgrade -y
      - run: sudo apt-get install ansible git
      - checkout
      - run:
          name: "run ansible-playbook for continuous integration"
          command: sudo ansible-playbook cloudbox.yml --tags "cloudbox" --skip-tags "settings" --extra-vars '{"continuous_integration":true}'
