version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - run: apt-get update
      - run: apt-get install software-properties-common python-software-properties python3-software-properties -y
      - run: apt-add-repository ppa:ansible/ansible -y
      - run: add-apt-repository ppa:git-core/ppa -y
      - run: apt-get update
      - run: apt-get upgrade -y
      - run: apt-get install ansible git -y
      - checkout
      - run:
          name: "run ansible-playbook for continuous integration"
          command: sudo ansible-playbook cloudbox.yml --tags "cloudbox" --skip-tags "settings" --extra-vars '{"continuous_integration":true}'
