#########################################################################
# Title:         Emby: Sanity Check                                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Set `emby_default_version` variable
  set_fact:
    emby_default_version: "latest"

- name: Check if 'emby.version' was specified
  set_fact:
    emby_version_is_specified: "{{ true if not (
        (emby is undefined)
        or
        (emby is none)
        or
        (emby | trim == '')
        or
        (emby.version is undefined)
        or
        (emby.version is none)
        or
        (emby.version | trim == '')
      )
      else false }}"

- name: Validate and set proper 'emby' key variables
  set_fact:
    emby_tmp: { version: "{{ (emby.version) if ((emby_version_is_specified) and (emby.version != 'default') and ((emby.version == 'latest') or (emby.version == 'beta'))) else (emby_default_version) }}" }

- name: Merge changes back to 'emby' key
  set_fact:
    emby: "{{ (emby_tmp) if (
              (emby is undefined)
              or
              (emby is none)
              or
              (emby | trim == '')
            )
            else ((emby) | combine(emby_tmp))  }}"

- name: Display issue with version chosen
  debug:
    msg: "Invalid Emby version tag. Using the default tag ({{emby_default_version}}) instead."
  when: (not emby_version_is_specified) or ((emby_version_is_specified) and not ((emby.version == 'default') or (emby.version == 'latest') or (emby.version == 'beta')))
