##########################################################################
# Title:         Cloudbox: Plex - DB Cache Size Settings                 #
# Author(s):     Desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Wait for Plex DB to be created
  wait_for:
    path: "/opt/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db"
    state: present

- name: Get Current Plex DB Cache Size
  shell: sqlite3 "/opt/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db" "PRAGMA default_cache_size;"
  args:
    executable: /bin/bash
  register: current_db_cache_size

- name: Get Desired Plex DB Cache Size
  set_fact:
    desired_db_cache_size: "{{ '2000' if ( plex.db_cache_size == 'default' ) else ( plex.db_cache_size | regex_replace(',', '') | int ) }}"
  register: desired_db_cache

- name: Make Plex DB Edits
  block:

  - name: Stop Plex Container
    docker_container:
      name: plex
      state: stopped

  - name: "Set Plex DB Cache Size to '{{ desired_db_cache_size | regex_replace(',', '') | int }}'"
    shell: "sqlite3 \"/opt/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db\" \"PRAGMA default_cache_size = '{{ desired_db_cache_size | regex_replace(',', '') | int }}';\""
    args:
      executable: /bin/bash

  - name: Get Current Plex DB Cache Size
    shell: sqlite3 "/opt/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db" "PRAGMA default_cache_size;"
    args:
      executable: /bin/bash
    register: new_db_cache_size

  - name: Display Current Plex DB Cache Size
    debug:
      msg: "Plex DB cache size is now set to '{{ new_db_cache_size.stdout | int }}'."

  - name: Start Plex Container
    docker_container:
      name: plex
      state: started

  when: ( current_db_cache_size.stdout | int ) != ( desired_db_cache_size | regex_replace(',', '') | int )
